/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import {
  toValue,
  unref
} from 'vue';
import type {
  MaybeRefOrGetter
} from 'vue';

import type {
  CatalogHealth,
  DealRead,
  FreeGameRead,
  HTTPValidationError,
  ListDealsApiV1CatalogDealsGetParams,
  RefreshStatus,
  StoreRead
} from '../model';

import { http } from '../../lib/http';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type listStoresApiV1CatalogStoresGetResponse200 = {
  data: StoreRead[]
  status: 200
}

export type listStoresApiV1CatalogStoresGetResponseSuccess = (listStoresApiV1CatalogStoresGetResponse200) & {
  headers: Headers;
};
;

export type listStoresApiV1CatalogStoresGetResponse = (listStoresApiV1CatalogStoresGetResponseSuccess)

export const getListStoresApiV1CatalogStoresGetUrl = () => {




  return `/api/v1/catalog/stores`
}

/**
 * @summary List observed stores
 */
export const listStoresApiV1CatalogStoresGet = async ( options?: Parameters<typeof http>[1]): Promise<listStoresApiV1CatalogStoresGetResponse> => {

  return http<listStoresApiV1CatalogStoresGetResponse>(getListStoresApiV1CatalogStoresGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListStoresApiV1CatalogStoresGetQueryKey = () => {
    return [
    'api','v1','catalog','stores'
    ] as const;
    }


export const getListStoresApiV1CatalogStoresGetQueryOptions = <TData = Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListStoresApiV1CatalogStoresGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>> = ({ signal }) => listStoresApiV1CatalogStoresGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>, TError, TData>
}

export type ListStoresApiV1CatalogStoresGetQueryResult = NonNullable<Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>>
export type ListStoresApiV1CatalogStoresGetQueryError = unknown


/**
 * @summary List observed stores
 */

export function useListStoresApiV1CatalogStoresGet<TData = Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStoresApiV1CatalogStoresGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStoresApiV1CatalogStoresGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export type listDealsApiV1CatalogDealsGetResponse200 = {
  data: DealRead[]
  status: 200
}

export type listDealsApiV1CatalogDealsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listDealsApiV1CatalogDealsGetResponseSuccess = (listDealsApiV1CatalogDealsGetResponse200) & {
  headers: Headers;
};
export type listDealsApiV1CatalogDealsGetResponseError = (listDealsApiV1CatalogDealsGetResponse422) & {
  headers: Headers;
};

export type listDealsApiV1CatalogDealsGetResponse = (listDealsApiV1CatalogDealsGetResponseSuccess | listDealsApiV1CatalogDealsGetResponseError)

export const getListDealsApiV1CatalogDealsGetUrl = (params?: ListDealsApiV1CatalogDealsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["store"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/catalog/deals?${stringifiedParams}` : `/api/v1/catalog/deals`
}

/**
 * @summary List current deals
 */
export const listDealsApiV1CatalogDealsGet = async (params?: ListDealsApiV1CatalogDealsGetParams, options?: Parameters<typeof http>[1]): Promise<listDealsApiV1CatalogDealsGetResponse> => {

  return http<listDealsApiV1CatalogDealsGetResponse>(getListDealsApiV1CatalogDealsGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListDealsApiV1CatalogDealsGetQueryKey = (params?: MaybeRefOrGetter<ListDealsApiV1CatalogDealsGetParams>,) => {
    return [
    'api','v1','catalog','deals', ...(params ? [params] : [])
    ] as const;
    }


export const getListDealsApiV1CatalogDealsGetQueryOptions = <TData = Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>, TError = HTTPValidationError>(params?: MaybeRefOrGetter<ListDealsApiV1CatalogDealsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListDealsApiV1CatalogDealsGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>> = ({ signal }) => listDealsApiV1CatalogDealsGet(toValue(params), { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>, TError, TData>
}

export type ListDealsApiV1CatalogDealsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>>
export type ListDealsApiV1CatalogDealsGetQueryError = HTTPValidationError


/**
 * @summary List current deals
 */

export function useListDealsApiV1CatalogDealsGet<TData = Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>, TError = HTTPValidationError>(
 params?: MaybeRefOrGetter<ListDealsApiV1CatalogDealsGetParams>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDealsApiV1CatalogDealsGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDealsApiV1CatalogDealsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export type listFreeGamesApiV1CatalogFreeGamesGetResponse200 = {
  data: FreeGameRead[]
  status: 200
}

export type listFreeGamesApiV1CatalogFreeGamesGetResponseSuccess = (listFreeGamesApiV1CatalogFreeGamesGetResponse200) & {
  headers: Headers;
};
;

export type listFreeGamesApiV1CatalogFreeGamesGetResponse = (listFreeGamesApiV1CatalogFreeGamesGetResponseSuccess)

export const getListFreeGamesApiV1CatalogFreeGamesGetUrl = () => {




  return `/api/v1/catalog/free-games`
}

/**
 * @summary List currently free games
 */
export const listFreeGamesApiV1CatalogFreeGamesGet = async ( options?: Parameters<typeof http>[1]): Promise<listFreeGamesApiV1CatalogFreeGamesGetResponse> => {

  return http<listFreeGamesApiV1CatalogFreeGamesGetResponse>(getListFreeGamesApiV1CatalogFreeGamesGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFreeGamesApiV1CatalogFreeGamesGetQueryKey = () => {
    return [
    'api','v1','catalog','free-games'
    ] as const;
    }


export const getListFreeGamesApiV1CatalogFreeGamesGetQueryOptions = <TData = Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getListFreeGamesApiV1CatalogFreeGamesGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>> = ({ signal }) => listFreeGamesApiV1CatalogFreeGamesGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>, TError, TData>
}

export type ListFreeGamesApiV1CatalogFreeGamesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>>
export type ListFreeGamesApiV1CatalogFreeGamesGetQueryError = unknown


/**
 * @summary List currently free games
 */

export function useListFreeGamesApiV1CatalogFreeGamesGet<TData = Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listFreeGamesApiV1CatalogFreeGamesGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListFreeGamesApiV1CatalogFreeGamesGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}






export type triggerRefreshApiV1CatalogRefreshPostResponse200 = {
  data: RefreshStatus
  status: 200
}

export type triggerRefreshApiV1CatalogRefreshPostResponseSuccess = (triggerRefreshApiV1CatalogRefreshPostResponse200) & {
  headers: Headers;
};
;

export type triggerRefreshApiV1CatalogRefreshPostResponse = (triggerRefreshApiV1CatalogRefreshPostResponseSuccess)

export const getTriggerRefreshApiV1CatalogRefreshPostUrl = () => {




  return `/api/v1/catalog/refresh`
}

/**
 * @summary Trigger immediate scrape of all active stores
 */
export const triggerRefreshApiV1CatalogRefreshPost = async ( options?: Parameters<typeof http>[1]): Promise<triggerRefreshApiV1CatalogRefreshPostResponse> => {

  return http<triggerRefreshApiV1CatalogRefreshPostResponse>(getTriggerRefreshApiV1CatalogRefreshPostUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getTriggerRefreshApiV1CatalogRefreshPostMutationKey = () => ['triggerRefreshApiV1CatalogRefreshPost'] as const;

export const getTriggerRefreshApiV1CatalogRefreshPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>, TError,void, TContext>, request?: SecondParameter<typeof http>}
): UseMutationOptions<Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>, TError,void, TContext> => {

const mutationKey = getTriggerRefreshApiV1CatalogRefreshPostMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>, void> = () => {


          return  triggerRefreshApiV1CatalogRefreshPost(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TriggerRefreshApiV1CatalogRefreshPostMutationResult = NonNullable<Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>>

    export type TriggerRefreshApiV1CatalogRefreshPostMutationError = unknown


    /**
 * @summary Trigger immediate scrape of all active stores
 */
export const useTriggerRefreshApiV1CatalogRefreshPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>, TError,void, TContext>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof triggerRefreshApiV1CatalogRefreshPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getTriggerRefreshApiV1CatalogRefreshPostMutationOptions(options), queryClient);
    }
    export type getHealthApiV1CatalogHealthGetResponse200 = {
  data: CatalogHealth
  status: 200
}

export type getHealthApiV1CatalogHealthGetResponseSuccess = (getHealthApiV1CatalogHealthGetResponse200) & {
  headers: Headers;
};
;

export type getHealthApiV1CatalogHealthGetResponse = (getHealthApiV1CatalogHealthGetResponseSuccess)

export const getGetHealthApiV1CatalogHealthGetUrl = () => {




  return `/api/v1/catalog/health`
}

/**
 * @summary Get the most recent scrape state per store
 */
export const getHealthApiV1CatalogHealthGet = async ( options?: Parameters<typeof http>[1]): Promise<getHealthApiV1CatalogHealthGetResponse> => {

  return http<getHealthApiV1CatalogHealthGetResponse>(getGetHealthApiV1CatalogHealthGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthApiV1CatalogHealthGetQueryKey = () => {
    return [
    'api','v1','catalog','health'
    ] as const;
    }


export const getGetHealthApiV1CatalogHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  getGetHealthApiV1CatalogHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>> = ({ signal }) => getHealthApiV1CatalogHealthGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>, TError, TData>
}

export type GetHealthApiV1CatalogHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>>
export type GetHealthApiV1CatalogHealthGetQueryError = unknown


/**
 * @summary Get the most recent scrape state per store
 */

export function useGetHealthApiV1CatalogHealthGet<TData = Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthApiV1CatalogHealthGet>>, TError, TData>>, request?: SecondParameter<typeof http>}
 , queryClient?: QueryClient
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthApiV1CatalogHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}
