/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */

export interface DealRead {
  title: string;
  listing_id: number;
  image_url: string | null;
  store_slug: string;
  store_display_name: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  base_amount: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  native_amount: string;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  kes_amount: string;
  currency: string;
  discount_percent: number | null;
  observed_at: string;
}
