/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */

export interface FreeGameRead {
  title: string;
  listing_id: number;
  image_url: string | null;
  store_slug: string;
  store_display_name: string;
  currency: string;
  base_amount: string | null;
  observed_at: string;
}
