/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */

export type ListDealsApiV1CatalogDealsGetParams = {
store?: string[] | null;
max_kes_price?: number | string | null;
min_discount_percent?: number | null;
q?: string | null;
};
