/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */
import type { StoreScrapeStatus } from './storeScrapeStatus';

export interface RefreshStatus {
  started_at: string;
  stores: StoreScrapeStatus[];
}
