/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */

export type ScrapeStatus = typeof ScrapeStatus[keyof typeof ScrapeStatus];


export const ScrapeStatus = {
  running: 'running',
  success: 'success',
  error: 'error',
} as const;
