/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */
import type { ScrapeStatus } from './scrapeStatus';

export interface StoreScrapeStatus {
  store_slug: string;
  status: ScrapeStatus;
  listings_observed: number;
  error_message: string | null;
  started_at: string;
  last_scrape_at: string | null;
}
