/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Fynd
 * OpenAPI spec version: 0.1.0
 */

export interface StoreRead {
  id: number;
  slug: string;
  display_name: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
